### ISSUE TITLE
demo启动扫码登录后空指针

### ISSUE THREAD

**Issue by qq727127158** [yaphone/itchat4jdemo#10]
java.lang.NullPointerException
	at cn.zhouyafeng.itchat4j.service.impl.LoginServiceImpl.processLoginInfo(LoginServiceImpl.java:393)
	at cn.zhouyafeng.itchat4j.service.impl.LoginServiceImpl.login(LoginServiceImpl.java:87)
	at cn.zhouyafeng.itchat4j.controller.LoginController.login(LoginController.java:50)
	at cn.zhouyafeng.itchat4j.Wechat.<init>(Wechat.java:20)
	at itchat4jtest.demo.demo1.Mytest.main(Mytest.java:17)

**Comment by nakedheart32** [comment]
我也是同样的问题，请问后来解决了吗

**Comment by Qi0816** [comment]
同问！！！！

**Comment by beijan** [comment]
同问，空指针
